# Amostragem

**Amostragem é uma contagem ou medição de parte da população e é usada em estudos estatísticos**

Observação: Para coletar dados não tendenciosos, você
deve ter certeza de que a amostra represente a população

## Carregamento da base de dados

In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
dataset = pd.read_csv('census.csv')

In [3]:
dataset.shape

(32561, 15)

In [4]:
dataset.head()

age          workclass  final-weight  ... hour-per-week  native-country  income
0   39          State-gov         77516  ...            40   United-States   <=50K
1   50   Self-emp-not-inc         83311  ...            13   United-States   <=50K
2   38            Private        215646  ...            40   United-States   <=50K
3   53            Private        234721  ...            40   United-States   <=50K
4   28            Private        338409  ...            40            Cuba   <=50K

[5 rows x 15 columns]

In [5]:
dataset.tail()

age      workclass  final-weight  ... hour-per-week  native-country  income
32556   27        Private        257302  ...            38   United-States   <=50K
32557   40        Private        154374  ...            40   United-States    >50K
32558   58        Private        151910  ...            40   United-States   <=50K
32559   22        Private        201490  ...            20   United-States   <=50K
32560   52   Self-emp-inc        287927  ...            40   United-States    >50K

[5 rows x 15 columns]

## Amostragem aleatória simples

In [6]:
df_amostra_aleatoria_simples = dataset.sample(n = 100, random_state = 1)

In [7]:
df_amostra_aleatoria_simples.shape

(100, 15)

In [8]:
df_amostra_aleatoria_simples.head()

age          workclass  ...  native-country  income
9646    62   Self-emp-not-inc  ...   United-States   <=50K
709     18            Private  ...   United-States   <=50K
7385    25            Private  ...   United-States    >50K
16671   33            Private  ...   United-States   <=50K
21932   36            Private  ...   United-States   <=50K

[5 rows x 15 columns]

In [9]:
def amostragem_aleatoria_simples(dataset, amostras):
  return dataset.sample(n = amostras, random_state=1)

In [10]:
df_amostra_aleatoria_simples = amostragem_aleatoria_simples(dataset, 100)
df_amostra_aleatoria_simples.shape

(100, 15)

In [11]:
df_amostra_aleatoria_simples.head()

age          workclass  ...  native-country  income
9646    62   Self-emp-not-inc  ...   United-States   <=50K
709     18            Private  ...   United-States   <=50K
7385    25            Private  ...   United-States    >50K
16671   33            Private  ...   United-States   <=50K
21932   36            Private  ...   United-States   <=50K

[5 rows x 15 columns]

## Amostragem sistemática

In [13]:
dataset.shape

(32561, 15)

In [14]:
len(dataset) // 100

325

In [ ]:
random.seed(1)
random.randint(0, 325)

In [15]:
68 + 325

393

In [16]:
393 + 325

718

In [17]:
np.arange(68, len(dataset), step = 325)

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [18]:
def amostragem_sistematica(dataset, amostras):
  intervalo = len(dataset) // amostras
  random.seed(1)
  inicio = random.randint(0, intervalo)
  indices = np.arange(inicio, len(dataset), step = intervalo)
  amostra_sistematica = dataset.iloc[indices]
  return amostra_sistematica

In [19]:
df_amostra_sistematica = amostragem_sistematica(dataset, 100)
df_amostra_sistematica.shape

(100, 15)

In [20]:
df_amostra_sistematica.head()

age      workclass  final-weight  ... hour-per-week  native-country  income
68     49   Self-emp-inc        191681  ...            50   United-States    >50K
393    34      State-gov         98101  ...            45               ?    >50K
718    22        Private        214399  ...            15   United-States   <=50K
1043   44        Private        167005  ...            60   United-States    >50K
1368   52        Private        152234  ...            40           Japan    >50K

[5 rows x 15 columns]

## Amostragem por grupos

In [23]:
len(dataset) / 10

3256.1

In [24]:
grupos = []
id_grupo = 0
contagem = 0
for _ in dataset.iterrows():
  grupos.append(id_grupo)
  contagem += 1
  if contagem > 3256:
    contagem = 0
    id_grupo += 1

In [25]:
print(grupos)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [26]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248]))

In [27]:
np.shape(grupos), dataset.shape

((32561,), (32561, 15))

In [28]:
dataset['grupo'] = grupos

In [29]:
dataset.head()

age          workclass  final-weight  ...  native-country  income grupo
0   39          State-gov         77516  ...   United-States   <=50K     0
1   50   Self-emp-not-inc         83311  ...   United-States   <=50K     0
2   38            Private        215646  ...   United-States   <=50K     0
3   53            Private        234721  ...   United-States   <=50K     0
4   28            Private        338409  ...            Cuba   <=50K     0

[5 rows x 16 columns]

In [30]:
dataset.tail()

age      workclass  final-weight  ...  native-country  income grupo
32556   27        Private        257302  ...   United-States   <=50K     9
32557   40        Private        154374  ...   United-States    >50K     9
32558   58        Private        151910  ...   United-States   <=50K     9
32559   22        Private        201490  ...   United-States   <=50K     9
32560   52   Self-emp-inc        287927  ...   United-States    >50K     9

[5 rows x 16 columns]

In [31]:
random.randint(0, 9)

9

In [32]:
df_agrupamento = dataset[dataset['grupo'] == 7]
df_agrupamento.shape

(3257, 16)

In [33]:
df_agrupamento['grupo'].value_counts()

7    3257
Name: grupo, dtype: int64

In [34]:
def amostragem_agrupamento(dataset, numero_grupos):
  intervalo = len(dataset) / numero_grupos

  grupos = []
  id_grupo = 0
  contagem = 0
  for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > intervalo:
      contagem = 0
      id_grupo += 1

  dataset['grupo'] = grupos
  random.seed(1)
  grupo_selecionado = random.randint(0, numero_grupos)
  return dataset[dataset['grupo'] == grupo_selecionado]

In [35]:
len(dataset) / 325

100.1876923076923

In [36]:
325 * 100

32500

In [37]:
df_amostra_agrupamento = amostragem_agrupamento(dataset, 325)
df_amostra_agrupamento.shape, df_amostra_agrupamento['grupo'].value_counts()

((101, 16), 68    101
 Name: grupo, dtype: int64)

In [38]:
df_amostra_agrupamento.head()

age workclass  final-weight  ...  native-country  income grupo
6868   32   Private        128016  ...   United-States   <=50K    68
6869   46   Private        360096  ...   United-States    >50K    68
6870   30   Private        170154  ...   United-States    >50K    68
6871   35   Private        337286  ...   United-States   <=50K    68
6872   52   Private        204322  ...   United-States   <=50K    68

[5 rows x 16 columns]

## Amostra estratificada

In [39]:
from sklearn.model_selection import StratifiedShuffleSplit

In [40]:
dataset['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [41]:
7841 / len(dataset), 24720 / len(dataset)

(0.2408095574460244, 0.7591904425539756)

In [42]:
0.2408095574460244 + 0.7591904425539756

1.0

In [43]:
100 / len(dataset)

0.0030711587481956942

In [44]:
split = StratifiedShuffleSplit(test_size=0.0030711587481956942)
for x, y in split.split(dataset, dataset['income']):
  df_x = dataset.iloc[x]
  df_y = dataset.iloc[y]

In [45]:
df_x.shape, df_y.shape

((32461, 16), (100, 16))

In [46]:
df_y.head()

age   workclass  final-weight  ...  native-country  income grupo
30138   36     Private        190023  ...   United-States    >50K   298
19910   36     Private        132879  ...   United-States   <=50K   197
48      41   State-gov        101603  ...   United-States   <=50K     0
12517   35     Private         48404  ...   United-States   <=50K   123
3046    54     Private        220115  ...   United-States   <=50K    30

[5 rows x 16 columns]

In [47]:
df_y['income'].value_counts()

 <=50K    76
 >50K     24
Name: income, dtype: int64

In [48]:
def amostragem_estratificada(dataset, percentual):
  split = StratifiedShuffleSplit(test_size=percentual, random_state=1)
  for _, y in split.split(dataset, dataset['income']):
    df_y = dataset.iloc[y]
  return df_y

In [49]:
df_amostra_estratificada = amostragem_estratificada(dataset, 0.0030711587481956942)
df_amostra_estratificada.shape

(100, 16)

## Comparativo dos resultados

In [50]:
dataset['age'].mean()

38.58164675532078

In [51]:
df_amostra_aleatoria_simples['age'].mean()

39.41

In [52]:
df_amostra_sistematica['age'].mean()

37.57

In [53]:
df_amostra_agrupamento['age'].mean()

40.06930693069307

In [54]:
df_amostra_estratificada['age'].mean()

36.9